spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:192.168.5.237}:${DB_PORT:3306}/${DB_NAME:test}
    username: ${DB_USER_NAME:root}
    password: ${DB_PWD:sa123;}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # create 启动时清空数据表，并重新创建。
    # create-drop 启动时生成表，sessionFactory关闭时表删除。
    # update 启动时根据实体类生产表，实体类属性变动时，表结构也会更新，在初期开发阶段使用此选项。
    # validate 启动时验证实体类和数据表是否一致，在数据结果稳定时采用此选项。
    # none 不采取任何措施。
    show-sql: true
    hibernate:
      ddl-auto: update
  # 让控制台输出的json格式更美观
  jackson:
    serialization:
      indent_output: true